### ISSUE TITLE
Git Buttons

### ISSUE THREAD

**Issue by KingPixil** [FootballCoder/YearOfCode#4]
They are from [usewing.ml](http://usewing.ml). And the star button is very far from the fork button, kind of bad looking.

Try custom generating your OWN at [GhBtns](http://ghbtns.com/), for your own needs. :+1:

**Comment by FootballCoder** [comment]
Ok, thanks for giving me the link, Appreciated!

**Comment by FootballCoder** [comment]
I'll fix it ASAP

**Comment by KingPixil** [comment]
@FootballCoder :+1:
